### ISSUE TITLE
Request to be added as package maintainer

### ISSUE THREAD

**Issue by aarondettmann** [conda-forge/ambiance-feedstock#4]
Hi! Thanks again for creating the Conda package for this small library. If your offer still stands, I'd like to be added as a maintainer for this feedstock. See our previous discussion: https://github.com/airinnova/ambiance/pull/7.

Best regards,
Aaron

**Comment by bryanwweber** [comment]
Sure! You can make a pull request to add your GitHub username to the list of maintainers at the bottom of `recipes/meta.yaml`

**Comment by bryanwweber** [comment]
Closed by #5
